version: '3.8'
services:
  chinachu-operator:
    image: chinachu:latest
    build:
        context: chinachu
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./chinachu/conf/config.json:/home/node/chinachu/config.json
     - ./chinachu/conf/rules.json:/home/node/chinachu/rules.json
     - ./chinachu/data:/home/node/chinachu/data
     - ./recorded:/home/node/chinachu/recorded
     - ./log:/home/node/chinachu/log
    command: app-operator.js
  chinachu-wui:
    image: chinachu:latest
    build:
        context: chinachu
    ports:
     - "20772:20772"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./chinachu/conf/config.json:/home/node/chinachu/config.json
     - ./chinachu/conf/rules.json:/home/node/chinachu/rules.json
     - ./chinachu/data:/home/node/chinachu/data
     - ./recorded:/home/node/chinachu/recorded
     - ./log:/home/node/chinachu/log
    command: app-wui.js
